"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.21.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.group import Group
from neucore_api.model.role import Role
globals()['Group'] = Group
globals()['Role'] = Role
from neucore_api.model.app import App


class TestApp(unittest.TestCase):
    """App unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApp(self):
        """Test App"""
        # FIXME: construct object with mandatory attributes with example values
        # model = App()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
