"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.26.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.eve_login import EveLogin


class TestEveLogin(unittest.TestCase):
    """EveLogin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEveLogin(self):
        """Test EveLogin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EveLogin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
