# coding: utf-8

"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.14.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neucore_api
from neucore_api.api.application___tracking_api import ApplicationTrackingApi  # noqa: E501
from neucore_api.rest import ApiException


class TestApplicationTrackingApi(unittest.TestCase):
    """ApplicationTrackingApi unit test stubs"""

    def setUp(self):
        self.api = neucore_api.api.application___tracking_api.ApplicationTrackingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_member_tracking_v1(self):
        """Test case for member_tracking_v1

        Return corporation member tracking data.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
