"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.33.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.character_name_change import CharacterNameChange


class TestCharacterNameChange(unittest.TestCase):
    """CharacterNameChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCharacterNameChange(self):
        """Test CharacterNameChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CharacterNameChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
