# coding: utf-8

"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.4.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neucore_api
from neucore_api.models.esi_location import EsiLocation  # noqa: E501
from neucore_api.rest import ApiException


class TestEsiLocation(unittest.TestCase):
    """EsiLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEsiLocation(self):
        """Test EsiLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neucore_api.models.esi_location.EsiLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
