# coding: utf-8

"""
    Brave Collective Core Services API

    Client library of Brave Collective Core Services API  # noqa: E501

    OpenAPI spec version: 0.7.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neucore_api
from neucore_api.models.removed_character import RemovedCharacter  # noqa: E501
from neucore_api.rest import ApiException


class TestRemovedCharacter(unittest.TestCase):
    """RemovedCharacter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemovedCharacter(self):
        """Test RemovedCharacter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neucore_api.models.removed_character.RemovedCharacter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
