# coding: utf-8

"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.14.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neucore_api
from neucore_api.api.application___groups_api import ApplicationGroupsApi  # noqa: E501
from neucore_api.rest import ApiException


class TestApplicationGroupsApi(unittest.TestCase):
    """ApplicationGroupsApi unit test stubs"""

    def setUp(self):
        self.api = neucore_api.api.application___groups_api.ApplicationGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_alliance_groups_bulk_v1(self):
        """Test case for alliance_groups_bulk_v1

        Return groups of multiple alliances.  # noqa: E501
        """
        pass

    def test_alliance_groups_v1(self):
        """Test case for alliance_groups_v1

        Return groups of the alliance.  # noqa: E501
        """
        pass

    def test_alliance_groups_v2(self):
        """Test case for alliance_groups_v2

        Return groups of the alliance.  # noqa: E501
        """
        pass

    def test_corp_groups_bulk_v1(self):
        """Test case for corp_groups_bulk_v1

        Return groups of multiple corporations.  # noqa: E501
        """
        pass

    def test_corp_groups_v1(self):
        """Test case for corp_groups_v1

        Return groups of the corporation.  # noqa: E501
        """
        pass

    def test_corp_groups_v2(self):
        """Test case for corp_groups_v2

        Return groups of the corporation.  # noqa: E501
        """
        pass

    def test_groups_bulk_v1(self):
        """Test case for groups_bulk_v1

        Return groups of multiple players, identified by one of their character IDs.  # noqa: E501
        """
        pass

    def test_groups_v1(self):
        """Test case for groups_v1

        Return groups of the character's player account.  # noqa: E501
        """
        pass

    def test_groups_v2(self):
        """Test case for groups_v2

        Return groups of the character's player account.  # noqa: E501
        """
        pass

    def test_groups_with_fallback_v1(self):
        """Test case for groups_with_fallback_v1

        Returns groups from the character's account, if available, or the corporation and alliance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
