"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.33.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.monthly_app_requests import MonthlyAppRequests


class TestMonthlyAppRequests(unittest.TestCase):
    """MonthlyAppRequests unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonthlyAppRequests(self):
        """Test MonthlyAppRequests"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonthlyAppRequests()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
