"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.21.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.system_variable import SystemVariable


class TestSystemVariable(unittest.TestCase):
    """SystemVariable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemVariable(self):
        """Test SystemVariable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemVariable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
