"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.21.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.group import Group
globals()['Group'] = Group
from neucore_api.model.alliance import Alliance


class TestAlliance(unittest.TestCase):
    """Alliance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlliance(self):
        """Test Alliance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Alliance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
