"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.33.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import neucore_api
from neucore_api.api.application_esi_api import ApplicationESIApi  # noqa: E501


class TestApplicationESIApi(unittest.TestCase):
    """ApplicationESIApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationESIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esi_eve_login_characters_v1(self):
        """Test case for esi_eve_login_characters_v1

        Returns character IDs of characters that have a valid ESI token of the specified EVE login.  # noqa: E501
        """
        pass

    def test_esi_post_v1(self):
        """Test case for esi_post_v1

        See POST /app/v2/esi  # noqa: E501
        """
        pass

    def test_esi_post_v2(self):
        """Test case for esi_post_v2

        Same as GET /app/v2/esi, but for POST requests.  # noqa: E501
        """
        pass

    def test_esi_v1(self):
        """Test case for esi_v1

        See GET /app/v2/esi  # noqa: E501
        """
        pass

    def test_esi_v2(self):
        """Test case for esi_v2

        Makes an ESI GET request on behalf on an EVE character and returns the result.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
