"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.26.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.esi_location import EsiLocation


class TestEsiLocation(unittest.TestCase):
    """EsiLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEsiLocation(self):
        """Test EsiLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EsiLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
