"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.26.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.character import Character
from neucore_api.model.esi_location import EsiLocation
from neucore_api.model.esi_type import EsiType
from neucore_api.model.player import Player
globals()['Character'] = Character
globals()['EsiLocation'] = EsiLocation
globals()['EsiType'] = EsiType
globals()['Player'] = Player
from neucore_api.model.corporation_member import CorporationMember


class TestCorporationMember(unittest.TestCase):
    """CorporationMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCorporationMember(self):
        """Test CorporationMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CorporationMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
