"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.21.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.service_configuration import ServiceConfiguration
globals()['ServiceConfiguration'] = ServiceConfiguration
from neucore_api.model.service import Service


class TestService(unittest.TestCase):
    """Service unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testService(self):
        """Test Service"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Service()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
