"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.33.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.total_daily_app_requests import TotalDailyAppRequests


class TestTotalDailyAppRequests(unittest.TestCase):
    """TotalDailyAppRequests unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTotalDailyAppRequests(self):
        """Test TotalDailyAppRequests"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TotalDailyAppRequests()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
