"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.33.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.alliance import Alliance
from neucore_api.model.group import Group
globals()['Alliance'] = Alliance
globals()['Group'] = Group
from neucore_api.model.corporation import Corporation


class TestCorporation(unittest.TestCase):
    """Corporation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCorporation(self):
        """Test Corporation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Corporation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
