"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.26.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neucore_api
from neucore_api.model.player_login_statistics import PlayerLoginStatistics


class TestPlayerLoginStatistics(unittest.TestCase):
    """PlayerLoginStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerLoginStatistics(self):
        """Test PlayerLoginStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlayerLoginStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
