"""
    Neucore API

    Client library of Neucore API

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from neucore_api.models.esi_access_token import EsiAccessToken
from neucore_api.models.esi_token_data import EsiTokenData

from neucore_api.api_client import ApiClient, RequestSerialized
from neucore_api.api_response import ApiResponse
from neucore_api.rest import RESTResponseType


class ApplicationESIApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def esi_access_token_v1(
        self,
        character_id: Annotated[StrictInt, Field(description="The EVE character ID.")],
        eve_login_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Optional EVE login name, defaults to 'core.default'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> EsiAccessToken:
        """Returns an access token for a character and EVE login that is valid for at least 60 seconds.

        Needs role: app-esi-token

        :param character_id: The EVE character ID. (required)
        :type character_id: int
        :param eve_login_name: Optional EVE login name, defaults to 'core.default'.
        :type eve_login_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_access_token_v1_serialize(
            character_id=character_id,
            eve_login_name=eve_login_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EsiAccessToken",
            '204': "str",
            '403': "str",
            '404': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def esi_access_token_v1_with_http_info(
        self,
        character_id: Annotated[StrictInt, Field(description="The EVE character ID.")],
        eve_login_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Optional EVE login name, defaults to 'core.default'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[EsiAccessToken]:
        """Returns an access token for a character and EVE login that is valid for at least 60 seconds.

        Needs role: app-esi-token

        :param character_id: The EVE character ID. (required)
        :type character_id: int
        :param eve_login_name: Optional EVE login name, defaults to 'core.default'.
        :type eve_login_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_access_token_v1_serialize(
            character_id=character_id,
            eve_login_name=eve_login_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EsiAccessToken",
            '204': "str",
            '403': "str",
            '404': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def esi_access_token_v1_without_preload_content(
        self,
        character_id: Annotated[StrictInt, Field(description="The EVE character ID.")],
        eve_login_name: Annotated[Optional[Annotated[str, Field(strict=True, max_length=20)]], Field(description="Optional EVE login name, defaults to 'core.default'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns an access token for a character and EVE login that is valid for at least 60 seconds.

        Needs role: app-esi-token

        :param character_id: The EVE character ID. (required)
        :type character_id: int
        :param eve_login_name: Optional EVE login name, defaults to 'core.default'.
        :type eve_login_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_access_token_v1_serialize(
            character_id=character_id,
            eve_login_name=eve_login_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EsiAccessToken",
            '204': "str",
            '403': "str",
            '404': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _esi_access_token_v1_serialize(
        self,
        character_id,
        eve_login_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if character_id is not None:
            _path_params['characterId'] = character_id
        # process the query parameters
        if eve_login_name is not None:
            
            _query_params.append(('eveLoginName', eve_login_name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/app/v1/esi/access-token/{characterId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def esi_eve_login_characters_v1(
        self,
        name: Annotated[str, Field(strict=True, max_length=20, description="EVE login name.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[int]:
        """Returns character IDs of characters that have an ESI token (including invalid) of an EVE login.

        Needs role: app-esi-login.

        :param name: EVE login name. (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_eve_login_characters_v1_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '403': "str",
            '404': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def esi_eve_login_characters_v1_with_http_info(
        self,
        name: Annotated[str, Field(strict=True, max_length=20, description="EVE login name.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[int]]:
        """Returns character IDs of characters that have an ESI token (including invalid) of an EVE login.

        Needs role: app-esi-login.

        :param name: EVE login name. (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_eve_login_characters_v1_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '403': "str",
            '404': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def esi_eve_login_characters_v1_without_preload_content(
        self,
        name: Annotated[str, Field(strict=True, max_length=20, description="EVE login name.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns character IDs of characters that have an ESI token (including invalid) of an EVE login.

        Needs role: app-esi-login.

        :param name: EVE login name. (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_eve_login_characters_v1_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '403': "str",
            '404': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _esi_eve_login_characters_v1_serialize(
        self,
        name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if name is not None:
            _path_params['name'] = name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/app/v1/esi/eve-login/{name}/characters',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def esi_eve_login_token_data_v1(
        self,
        name: Annotated[str, Field(strict=True, max_length=20, description="EVE login name, 'core.default' is not allowed.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[EsiTokenData]:
        """Returns data for all valid tokens (roles are also checked if applicable) for an EVE login. This returns cached data, it does not check if the token is still valid.

        Needs role: app-esi-login.

        :param name: EVE login name, 'core.default' is not allowed. (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_eve_login_token_data_v1_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[EsiTokenData]",
            '403': "str",
            '404': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def esi_eve_login_token_data_v1_with_http_info(
        self,
        name: Annotated[str, Field(strict=True, max_length=20, description="EVE login name, 'core.default' is not allowed.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[EsiTokenData]]:
        """Returns data for all valid tokens (roles are also checked if applicable) for an EVE login. This returns cached data, it does not check if the token is still valid.

        Needs role: app-esi-login.

        :param name: EVE login name, 'core.default' is not allowed. (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_eve_login_token_data_v1_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[EsiTokenData]",
            '403': "str",
            '404': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def esi_eve_login_token_data_v1_without_preload_content(
        self,
        name: Annotated[str, Field(strict=True, max_length=20, description="EVE login name, 'core.default' is not allowed.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns data for all valid tokens (roles are also checked if applicable) for an EVE login. This returns cached data, it does not check if the token is still valid.

        Needs role: app-esi-login.

        :param name: EVE login name, 'core.default' is not allowed. (required)
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_eve_login_token_data_v1_serialize(
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[EsiTokenData]",
            '403': "str",
            '404': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _esi_eve_login_token_data_v1_serialize(
        self,
        name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if name is not None:
            _path_params['name'] = name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/app/v1/esi/eve-login/{name}/token-data',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def esi_post_v1(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        body: StrictStr,
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """(Deprecated) See POST /app/v2/esi. The only difference are the return values in case of errors.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param body:  (required)
        :type body: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("POST /app/v1/esi is deprecated.", DeprecationWarning)

        _param = self._esi_post_v1_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            body=body,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def esi_post_v1_with_http_info(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        body: StrictStr,
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """(Deprecated) See POST /app/v2/esi. The only difference are the return values in case of errors.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param body:  (required)
        :type body: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("POST /app/v1/esi is deprecated.", DeprecationWarning)

        _param = self._esi_post_v1_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            body=body,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def esi_post_v1_without_preload_content(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        body: StrictStr,
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """(Deprecated) See POST /app/v2/esi. The only difference are the return values in case of errors.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param body:  (required)
        :type body: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("POST /app/v1/esi is deprecated.", DeprecationWarning)

        _param = self._esi_post_v1_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            body=body,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _esi_post_v1_serialize(
        self,
        esi_path_query,
        datasource,
        body,
        neucore_eve_character,
        neucore_eve_login,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if esi_path_query is not None:
            
            _query_params.append(('esi-path-query', esi_path_query))
            
        if datasource is not None:
            
            _query_params.append(('datasource', datasource))
            
        # process the header parameters
        if neucore_eve_character is not None:
            _header_params['Neucore-EveCharacter'] = neucore_eve_character
        if neucore_eve_login is not None:
            _header_params['Neucore-EveLogin'] = neucore_eve_login
        # process the form parameters
        # process the body parameter
        if body is not None:
            _body_params = body


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'text/plain'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/app/v1/esi',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def esi_post_v2(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        body: Annotated[StrictStr, Field(description="JSON encoded data.")],
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        x_compatibility_date: Annotated[Optional[StrictStr], Field(description="The ESI compatibility date.")] = None,
        accept_language: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Same as GET /app/v2/esi, but for POST requests.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param body: JSON encoded data. (required)
        :type body: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param x_compatibility_date: The ESI compatibility date.
        :type x_compatibility_date: str
        :param accept_language:
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_post_v2_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            body=body,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            x_compatibility_date=x_compatibility_date,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def esi_post_v2_with_http_info(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        body: Annotated[StrictStr, Field(description="JSON encoded data.")],
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        x_compatibility_date: Annotated[Optional[StrictStr], Field(description="The ESI compatibility date.")] = None,
        accept_language: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Same as GET /app/v2/esi, but for POST requests.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param body: JSON encoded data. (required)
        :type body: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param x_compatibility_date: The ESI compatibility date.
        :type x_compatibility_date: str
        :param accept_language:
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_post_v2_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            body=body,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            x_compatibility_date=x_compatibility_date,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def esi_post_v2_without_preload_content(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        body: Annotated[StrictStr, Field(description="JSON encoded data.")],
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        x_compatibility_date: Annotated[Optional[StrictStr], Field(description="The ESI compatibility date.")] = None,
        accept_language: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Same as GET /app/v2/esi, but for POST requests.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param body: JSON encoded data. (required)
        :type body: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param x_compatibility_date: The ESI compatibility date.
        :type x_compatibility_date: str
        :param accept_language:
        :type accept_language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_post_v2_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            body=body,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            x_compatibility_date=x_compatibility_date,
            accept_language=accept_language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _esi_post_v2_serialize(
        self,
        esi_path_query,
        datasource,
        body,
        neucore_eve_character,
        neucore_eve_login,
        x_compatibility_date,
        accept_language,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if esi_path_query is not None:
            
            _query_params.append(('esi-path-query', esi_path_query))
            
        if datasource is not None:
            
            _query_params.append(('datasource', datasource))
            
        # process the header parameters
        if neucore_eve_character is not None:
            _header_params['Neucore-EveCharacter'] = neucore_eve_character
        if neucore_eve_login is not None:
            _header_params['Neucore-EveLogin'] = neucore_eve_login
        if x_compatibility_date is not None:
            _header_params['X-Compatibility-Date'] = x_compatibility_date
        if accept_language is not None:
            _header_params['Accept-Language'] = accept_language
        # process the form parameters
        # process the body parameter
        if body is not None:
            _body_params = body


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'text/plain'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/app/v2/esi',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def esi_v1(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """(Deprecated) See GET /app/v2/esi. The only difference are the return values in case of errors.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("GET /app/v1/esi is deprecated.", DeprecationWarning)

        _param = self._esi_v1_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def esi_v1_with_http_info(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """(Deprecated) See GET /app/v2/esi. The only difference are the return values in case of errors.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("GET /app/v1/esi is deprecated.", DeprecationWarning)

        _param = self._esi_v1_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def esi_v1_without_preload_content(
        self,
        esi_path_query: StrictStr,
        datasource: StrictStr,
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """(Deprecated) See GET /app/v2/esi. The only difference are the return values in case of errors.


        :param esi_path_query: (required)
        :type esi_path_query: str
        :param datasource: (required)
        :type datasource: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501
        warnings.warn("GET /app/v1/esi is deprecated.", DeprecationWarning)

        _param = self._esi_v1_serialize(
            esi_path_query=esi_path_query,
            datasource=datasource,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _esi_v1_serialize(
        self,
        esi_path_query,
        datasource,
        neucore_eve_character,
        neucore_eve_login,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if esi_path_query is not None:
            
            _query_params.append(('esi-path-query', esi_path_query))
            
        if datasource is not None:
            
            _query_params.append(('datasource', datasource))
            
        # process the header parameters
        if neucore_eve_character is not None:
            _header_params['Neucore-EveCharacter'] = neucore_eve_character
        if neucore_eve_login is not None:
            _header_params['Neucore-EveLogin'] = neucore_eve_login
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/app/v1/esi',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def esi_v2(
        self,
        esi_path_query: Annotated[StrictStr, Field(description="The ESI path and query string (without the datasource parameter).")],
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        x_compatibility_date: Annotated[Optional[StrictStr], Field(description="The ESI compatibility date.")] = None,
        accept_language: Optional[StrictStr] = None,
        datasource: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used from the default login to make the ESI request. Optionally followed by a colon and the name of an EVE login to use an alternative ESI token.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Makes an ESI GET request on behalf on an EVE character and returns the result.

        Needs role: app-esi-proxy<br>Either the header 'Neucore-EveCharacter' and optionally 'Neucore-EveLogin' or the query parameter 'datasource' is required.<br> Public ESI routes are not allowed.<br>The following headers from ESI are passed through to the response if they exist: Content-Type, Expires, X-Esi-Error-Limit-Remain, X-Esi-Error-Limit-Reset, X-Ratelimit-Group, X-Ratelimit-Limit, X-Ratelimit-Remaining, X-Ratelimit-Used, Retry-After, X-Pages, before, after, X-Compatibility-Date, Warning. <br>The HTTP status code from ESI is also passed through, so there may be more than the documented ones.<br>The ESI path and query parameters can alternatively be appended to the path of this endpoint, this allows using OpenAPI clients generated for the EVE API (ESI), see doc/api-examples for more.

        :param esi_path_query: The ESI path and query string (without the datasource parameter). (required)
        :type esi_path_query: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param x_compatibility_date: The ESI compatibility date.
        :type x_compatibility_date: str
        :param accept_language:
        :type accept_language: str
        :param datasource: The EVE character ID those token should be used from the default login to make the ESI request. Optionally followed by a colon and the name of an EVE login to use an alternative ESI token.
        :type datasource: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_v2_serialize(
            esi_path_query=esi_path_query,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            x_compatibility_date=x_compatibility_date,
            accept_language=accept_language,
            datasource=datasource,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def esi_v2_with_http_info(
        self,
        esi_path_query: Annotated[StrictStr, Field(description="The ESI path and query string (without the datasource parameter).")],
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        x_compatibility_date: Annotated[Optional[StrictStr], Field(description="The ESI compatibility date.")] = None,
        accept_language: Optional[StrictStr] = None,
        datasource: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used from the default login to make the ESI request. Optionally followed by a colon and the name of an EVE login to use an alternative ESI token.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Makes an ESI GET request on behalf on an EVE character and returns the result.

        Needs role: app-esi-proxy<br>Either the header 'Neucore-EveCharacter' and optionally 'Neucore-EveLogin' or the query parameter 'datasource' is required.<br> Public ESI routes are not allowed.<br>The following headers from ESI are passed through to the response if they exist: Content-Type, Expires, X-Esi-Error-Limit-Remain, X-Esi-Error-Limit-Reset, X-Ratelimit-Group, X-Ratelimit-Limit, X-Ratelimit-Remaining, X-Ratelimit-Used, Retry-After, X-Pages, before, after, X-Compatibility-Date, Warning. <br>The HTTP status code from ESI is also passed through, so there may be more than the documented ones.<br>The ESI path and query parameters can alternatively be appended to the path of this endpoint, this allows using OpenAPI clients generated for the EVE API (ESI), see doc/api-examples for more.

        :param esi_path_query: The ESI path and query string (without the datasource parameter). (required)
        :type esi_path_query: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param x_compatibility_date: The ESI compatibility date.
        :type x_compatibility_date: str
        :param accept_language:
        :type accept_language: str
        :param datasource: The EVE character ID those token should be used from the default login to make the ESI request. Optionally followed by a colon and the name of an EVE login to use an alternative ESI token.
        :type datasource: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_v2_serialize(
            esi_path_query=esi_path_query,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            x_compatibility_date=x_compatibility_date,
            accept_language=accept_language,
            datasource=datasource,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def esi_v2_without_preload_content(
        self,
        esi_path_query: Annotated[StrictStr, Field(description="The ESI path and query string (without the datasource parameter).")],
        neucore_eve_character: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used. Has priority over the query parameter 'datasource'")] = None,
        neucore_eve_login: Annotated[Optional[StrictStr], Field(description="The EVE login name from which the token should be used, defaults to core.default.")] = None,
        x_compatibility_date: Annotated[Optional[StrictStr], Field(description="The ESI compatibility date.")] = None,
        accept_language: Optional[StrictStr] = None,
        datasource: Annotated[Optional[StrictStr], Field(description="The EVE character ID those token should be used from the default login to make the ESI request. Optionally followed by a colon and the name of an EVE login to use an alternative ESI token.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Makes an ESI GET request on behalf on an EVE character and returns the result.

        Needs role: app-esi-proxy<br>Either the header 'Neucore-EveCharacter' and optionally 'Neucore-EveLogin' or the query parameter 'datasource' is required.<br> Public ESI routes are not allowed.<br>The following headers from ESI are passed through to the response if they exist: Content-Type, Expires, X-Esi-Error-Limit-Remain, X-Esi-Error-Limit-Reset, X-Ratelimit-Group, X-Ratelimit-Limit, X-Ratelimit-Remaining, X-Ratelimit-Used, Retry-After, X-Pages, before, after, X-Compatibility-Date, Warning. <br>The HTTP status code from ESI is also passed through, so there may be more than the documented ones.<br>The ESI path and query parameters can alternatively be appended to the path of this endpoint, this allows using OpenAPI clients generated for the EVE API (ESI), see doc/api-examples for more.

        :param esi_path_query: The ESI path and query string (without the datasource parameter). (required)
        :type esi_path_query: str
        :param neucore_eve_character: The EVE character ID those token should be used. Has priority over the query parameter 'datasource'
        :type neucore_eve_character: str
        :param neucore_eve_login: The EVE login name from which the token should be used, defaults to core.default.
        :type neucore_eve_login: str
        :param x_compatibility_date: The ESI compatibility date.
        :type x_compatibility_date: str
        :param accept_language:
        :type accept_language: str
        :param datasource: The EVE character ID those token should be used from the default login to make the ESI request. Optionally followed by a colon and the name of an EVE login to use an alternative ESI token.
        :type datasource: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._esi_v2_serialize(
            esi_path_query=esi_path_query,
            neucore_eve_character=neucore_eve_character,
            neucore_eve_login=neucore_eve_login,
            x_compatibility_date=x_compatibility_date,
            accept_language=accept_language,
            datasource=datasource,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '304': None,
            '400': "str",
            '401': "str",
            '403': "str",
            '420': "str",
            '429': "str",
            '500': "str",
            '503': "str",
            '504': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _esi_v2_serialize(
        self,
        esi_path_query,
        neucore_eve_character,
        neucore_eve_login,
        x_compatibility_date,
        accept_language,
        datasource,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if esi_path_query is not None:
            
            _query_params.append(('esi-path-query', esi_path_query))
            
        if datasource is not None:
            
            _query_params.append(('datasource', datasource))
            
        # process the header parameters
        if neucore_eve_character is not None:
            _header_params['Neucore-EveCharacter'] = neucore_eve_character
        if neucore_eve_login is not None:
            _header_params['Neucore-EveLogin'] = neucore_eve_login
        if x_compatibility_date is not None:
            _header_params['X-Compatibility-Date'] = x_compatibility_date
        if accept_language is not None:
            _header_params['Accept-Language'] = accept_language
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/app/v2/esi',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


