# coding: utf-8

"""
    Neucore API

    Client library of Neucore API

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from neucore_api.models.eve_login import EveLogin
from neucore_api.models.group import Group
from neucore_api.models.role import Role
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class App(BaseModel):
    """
    App
    """ # noqa: E501
    id: Optional[StrictInt] = Field(description="App ID")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(description="App name")
    roles: Optional[List[Role]] = Field(default=None, description="Roles for authorisation.")
    groups: Optional[List[Group]] = Field(default=None, description="Groups the app can see.")
    eve_logins: Optional[List[EveLogin]] = Field(default=None, alias="eveLogins")
    __properties: ClassVar[List[str]] = ["id", "name", "roles", "groups", "eveLogins"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of App from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                _items.append(_item_groups.to_dict() if _item_groups is not None else None)
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in eve_logins (list)
        _items = []
        if self.eve_logins:
            for _item_eve_logins in self.eve_logins:
                _items.append(_item_eve_logins.to_dict() if _item_eve_logins is not None else None)
            _dict['eveLogins'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of App from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "roles": obj.get("roles"),
            "groups": [Group.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "eveLogins": [EveLogin.from_dict(_item) for _item in obj["eveLogins"]] if obj.get("eveLogins") is not None else None
        })
        return _obj


