# coding: utf-8

"""
    Neucore API

    Client library of Neucore API

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from neucore_api.models.alliance import Alliance
from neucore_api.models.group import Group
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Corporation(BaseModel):
    """
    EVE corporation.
    """ # noqa: E501
    id: Optional[StrictInt] = Field(description="EVE corporation ID.")
    name: Optional[StrictStr] = Field(description="EVE corporation name.")
    ticker: Optional[StrictStr] = Field(description="Corporation ticker.")
    alliance: Optional[Alliance] = None
    groups: Optional[List[Group]] = Field(default=None, description="Groups for automatic assignment (API: not included by default).")
    tracking_last_update: Optional[datetime] = Field(default=None, description="Last update of corporation member tracking data (API: not included by default).", alias="trackingLastUpdate")
    auto_allowlist: Optional[StrictBool] = Field(default=None, description="True if this corporation was automatically placed on the allowlist of a watchlist (API: not included by default).", alias="autoAllowlist")
    __properties: ClassVar[List[str]] = ["id", "name", "ticker", "alliance", "groups", "trackingLastUpdate", "autoAllowlist"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Corporation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alliance
        if self.alliance:
            _dict['alliance'] = self.alliance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                _items.append(_item_groups.to_dict() if _item_groups is not None else None)
            _dict['groups'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if ticker (nullable) is None
        # and model_fields_set contains the field
        if self.ticker is None and "ticker" in self.model_fields_set:
            _dict['ticker'] = None

        # set to None if tracking_last_update (nullable) is None
        # and model_fields_set contains the field
        if self.tracking_last_update is None and "tracking_last_update" in self.model_fields_set:
            _dict['trackingLastUpdate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Corporation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "ticker": obj.get("ticker"),
            "alliance": Alliance.from_dict(obj["alliance"]) if obj.get("alliance") is not None else None,
            "groups": [Group.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "trackingLastUpdate": obj.get("trackingLastUpdate"),
            "autoAllowlist": obj.get("autoAllowlist")
        })
        return _obj


