# coding: utf-8

"""
    Neucore API

    Client library of Neucore API

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from neucore_api.models.character import Character
from neucore_api.models.esi_location import EsiLocation
from neucore_api.models.esi_type import EsiType
from neucore_api.models.player import Player
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CorporationMember(BaseModel):
    """
    The player property contains only id and name, character does not contain corporation.
    """ # noqa: E501
    player: Optional[Player] = None
    id: Optional[StrictInt] = Field(description="EVE Character ID.")
    name: Optional[StrictStr] = Field(description="EVE Character name.")
    location: Optional[EsiLocation] = None
    logoff_date: Optional[datetime] = Field(default=None, alias="logoffDate")
    logon_date: Optional[datetime] = Field(default=None, alias="logonDate")
    ship_type: Optional[EsiType] = Field(default=None, alias="shipType")
    start_date: Optional[datetime] = Field(default=None, alias="startDate")
    character: Optional[Character] = None
    missing_character_mail_sent_date: Optional[datetime] = Field(default=None, description="Date and time of the last sent mail.", alias="missingCharacterMailSentDate")
    missing_character_mail_sent_result: Optional[StrictStr] = Field(default=None, description="Result of the last sent mail (OK, Blocked, CSPA charge > 0)", alias="missingCharacterMailSentResult")
    missing_character_mail_sent_number: Optional[StrictInt] = Field(default=None, description="Number of mails sent, is reset when the character is added.", alias="missingCharacterMailSentNumber")
    __properties: ClassVar[List[str]] = ["player", "id", "name", "location", "logoffDate", "logonDate", "shipType", "startDate", "character", "missingCharacterMailSentDate", "missingCharacterMailSentResult", "missingCharacterMailSentNumber"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CorporationMember from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ship_type
        if self.ship_type:
            _dict['shipType'] = self.ship_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of character
        if self.character:
            _dict['character'] = self.character.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if logoff_date (nullable) is None
        # and model_fields_set contains the field
        if self.logoff_date is None and "logoff_date" in self.model_fields_set:
            _dict['logoffDate'] = None

        # set to None if logon_date (nullable) is None
        # and model_fields_set contains the field
        if self.logon_date is None and "logon_date" in self.model_fields_set:
            _dict['logonDate'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['startDate'] = None

        # set to None if missing_character_mail_sent_date (nullable) is None
        # and model_fields_set contains the field
        if self.missing_character_mail_sent_date is None and "missing_character_mail_sent_date" in self.model_fields_set:
            _dict['missingCharacterMailSentDate'] = None

        # set to None if missing_character_mail_sent_result (nullable) is None
        # and model_fields_set contains the field
        if self.missing_character_mail_sent_result is None and "missing_character_mail_sent_result" in self.model_fields_set:
            _dict['missingCharacterMailSentResult'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CorporationMember from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "player": Player.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "location": EsiLocation.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "logoffDate": obj.get("logoffDate"),
            "logonDate": obj.get("logonDate"),
            "shipType": EsiType.from_dict(obj["shipType"]) if obj.get("shipType") is not None else None,
            "startDate": obj.get("startDate"),
            "character": Character.from_dict(obj["character"]) if obj.get("character") is not None else None,
            "missingCharacterMailSentDate": obj.get("missingCharacterMailSentDate"),
            "missingCharacterMailSentResult": obj.get("missingCharacterMailSentResult"),
            "missingCharacterMailSentNumber": obj.get("missingCharacterMailSentNumber")
        })
        return _obj


