# coding: utf-8

"""
    Neucore API

    Client library of Neucore API

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from neucore_api.models.app import App
from neucore_api.models.character import Character
from neucore_api.models.group import Group
from neucore_api.models.role import Role
from neucore_api.models.service_account import ServiceAccount
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Player(BaseModel):
    """
    Player
    """ # noqa: E501
    service_accounts: Optional[List[ServiceAccount]] = Field(default=None, description="External service accounts (API: not included by default)", alias="serviceAccounts")
    character_id: Optional[StrictInt] = Field(default=None, description="ID of main character (API: not included by default)", alias="characterId")
    corporation_name: Optional[StrictStr] = Field(default=None, description="Corporation of main character (API: not included by default)", alias="corporationName")
    alliance_name: Optional[StrictStr] = Field(default=None, description="Alliance of main character (API: not included by default)", alias="allianceName")
    id: Optional[StrictInt]
    name: StrictStr = Field(description="A name for the player.  This is the EVE character name of the current main character or the most recent main character, if there isn't one at the moment.")
    status: Optional[StrictStr] = Field(default=None, description="Player account status.")
    roles: Optional[List[Role]] = Field(default=None, description="Roles for authorisation.")
    characters: Optional[List[Character]] = None
    groups: Optional[List[Group]] = Field(default=None, description="Group membership.")
    manager_groups: Optional[List[Group]] = Field(default=None, description="Manager of groups.", alias="managerGroups")
    manager_apps: Optional[List[App]] = Field(default=None, description="Manager of apps.", alias="managerApps")
    removed_characters: Optional[List[RemovedCharacter]] = Field(default=None, description="Characters that were removed from a player (API: not included by default).", alias="removedCharacters")
    incoming_characters: Optional[List[RemovedCharacter]] = Field(default=None, description="Characters that were moved from another player account to this account (API: not included by default).", alias="incomingCharacters")
    __properties: ClassVar[List[str]] = ["serviceAccounts", "characterId", "corporationName", "allianceName", "id", "name", "status", "roles", "characters", "groups", "managerGroups", "managerApps", "removedCharacters", "incomingCharacters"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['standard', 'managed']):
            raise ValueError("must be one of enum values ('standard', 'managed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Player from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in service_accounts (list)
        _items = []
        if self.service_accounts:
            for _item_service_accounts in self.service_accounts:
                _items.append(_item_service_accounts.to_dict() if _item_service_accounts is not None else None)
            _dict['serviceAccounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in characters (list)
        _items = []
        if self.characters:
            for _item_characters in self.characters:
                _items.append(_item_characters.to_dict() if _item_characters is not None else None)
            _dict['characters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                _items.append(_item_groups.to_dict() if _item_groups is not None else None)
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in manager_groups (list)
        _items = []
        if self.manager_groups:
            for _item_manager_groups in self.manager_groups:
                _items.append(_item_manager_groups.to_dict() if _item_manager_groups is not None else None)
            _dict['managerGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in manager_apps (list)
        _items = []
        if self.manager_apps:
            for _item_manager_apps in self.manager_apps:
                _items.append(_item_manager_apps.to_dict() if _item_manager_apps is not None else None)
            _dict['managerApps'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in removed_characters (list)
        _items = []
        if self.removed_characters:
            for _item_removed_characters in self.removed_characters:
                _items.append(_item_removed_characters.to_dict() if _item_removed_characters is not None else None)
            _dict['removedCharacters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in incoming_characters (list)
        _items = []
        if self.incoming_characters:
            for _item_incoming_characters in self.incoming_characters:
                _items.append(_item_incoming_characters.to_dict() if _item_incoming_characters is not None else None)
            _dict['incomingCharacters'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Player from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "serviceAccounts": [ServiceAccount.from_dict(_item) for _item in obj["serviceAccounts"]] if obj.get("serviceAccounts") is not None else None,
            "characterId": obj.get("characterId"),
            "corporationName": obj.get("corporationName"),
            "allianceName": obj.get("allianceName"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "roles": obj.get("roles"),
            "characters": [Character.from_dict(_item) for _item in obj["characters"]] if obj.get("characters") is not None else None,
            "groups": [Group.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "managerGroups": [Group.from_dict(_item) for _item in obj["managerGroups"]] if obj.get("managerGroups") is not None else None,
            "managerApps": [App.from_dict(_item) for _item in obj["managerApps"]] if obj.get("managerApps") is not None else None,
            "removedCharacters": [RemovedCharacter.from_dict(_item) for _item in obj["removedCharacters"]] if obj.get("removedCharacters") is not None else None,
            "incomingCharacters": [RemovedCharacter.from_dict(_item) for _item in obj["incomingCharacters"]] if obj.get("incomingCharacters") is not None else None
        })
        return _obj

from neucore_api.models.removed_character import RemovedCharacter
# TODO: Rewrite to not use raise_errors
Player.model_rebuild(raise_errors=False)

