# coding: utf-8

"""
    Neucore API

    Client library of Neucore API

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from neucore_api.models.plugin_configuration_url import PluginConfigurationURL
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PluginConfigurationDatabase(BaseModel):
    """
    Plugin configuration stored in database.  API: The required properties are necessary for the service page where users register their account. The rest is necessary for the admin page.
    """ # noqa: E501
    directory_name: Optional[StrictStr] = Field(default=None, description="Directory where the plugin.yml file is stored.  Only from database but always set when the data from the file is read.", alias="directoryName")
    urls: List[PluginConfigurationURL] = Field(alias="URLs")
    text_top: StrictStr = Field(alias="textTop")
    text_account: StrictStr = Field(alias="textAccount")
    text_register: StrictStr = Field(alias="textRegister")
    text_pending: StrictStr = Field(alias="textPending")
    configuration_data: StrictStr = Field(alias="configurationData")
    active: Optional[StrictBool] = Field(default=None, description="Inactive plugins are neither updated by the cron job nor displayed to the user.  From admin UI.")
    required_groups: Optional[List[StrictInt]] = Field(default=None, description="From admin UI.", alias="requiredGroups")
    __properties: ClassVar[List[str]] = ["directoryName", "URLs", "textTop", "textAccount", "textRegister", "textPending", "configurationData", "active", "requiredGroups"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PluginConfigurationDatabase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in urls (list)
        _items = []
        if self.urls:
            for _item_urls in self.urls:
                _items.append(_item_urls.to_dict() if _item_urls is not None else None)
            _dict['URLs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PluginConfigurationDatabase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "directoryName": obj.get("directoryName"),
            "URLs": [PluginConfigurationURL.from_dict(_item) for _item in obj["URLs"]] if obj.get("URLs") is not None else None,
            "textTop": obj.get("textTop"),
            "textAccount": obj.get("textAccount"),
            "textRegister": obj.get("textRegister"),
            "textPending": obj.get("textPending"),
            "configurationData": obj.get("configurationData"),
            "active": obj.get("active"),
            "requiredGroups": obj.get("requiredGroups")
        })
        return _obj


