# coding: utf-8

"""
    Neucore API

    Client library of Neucore API

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RemovedCharacter(BaseModel):
    """
    RemovedCharacter
    """ # noqa: E501
    new_player_id: Optional[StrictInt] = Field(default=None, alias="newPlayerId")
    new_player_name: Optional[StrictStr] = Field(default=None, alias="newPlayerName")
    player: Optional[Player] = None
    character_id: Optional[StrictInt] = Field(description="EVE character ID.", alias="characterId")
    character_name: Optional[StrictStr] = Field(description="EVE character name.", alias="characterName")
    removed_date: Optional[datetime] = Field(description="Date of removal.", alias="removedDate")
    reason: Optional[StrictStr] = Field(description="How it was removed (deleted or moved to another account).")
    deleted_by: Optional[Player] = Field(default=None, alias="deletedBy")
    __properties: ClassVar[List[str]] = ["newPlayerId", "newPlayerName", "player", "characterId", "characterName", "removedDate", "reason", "deletedBy"]

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['moved', 'moved-owner-changed', 'deleted-biomassed', 'deleted-owner-changed', 'deleted-lost-access', 'deleted-manually']):
            raise ValueError("must be one of enum values ('moved', 'moved-owner-changed', 'deleted-biomassed', 'deleted-owner-changed', 'deleted-lost-access', 'deleted-manually')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RemovedCharacter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted_by
        if self.deleted_by:
            _dict['deletedBy'] = self.deleted_by.to_dict()
        # set to None if character_id (nullable) is None
        # and model_fields_set contains the field
        if self.character_id is None and "character_id" in self.model_fields_set:
            _dict['characterId'] = None

        # set to None if character_name (nullable) is None
        # and model_fields_set contains the field
        if self.character_name is None and "character_name" in self.model_fields_set:
            _dict['characterName'] = None

        # set to None if removed_date (nullable) is None
        # and model_fields_set contains the field
        if self.removed_date is None and "removed_date" in self.model_fields_set:
            _dict['removedDate'] = None

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RemovedCharacter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "newPlayerId": obj.get("newPlayerId"),
            "newPlayerName": obj.get("newPlayerName"),
            "player": Player.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "characterId": obj.get("characterId"),
            "characterName": obj.get("characterName"),
            "removedDate": obj.get("removedDate"),
            "reason": obj.get("reason"),
            "deletedBy": Player.from_dict(obj["deletedBy"]) if obj.get("deletedBy") is not None else None
        })
        return _obj

from neucore_api.models.player import Player
# TODO: Rewrite to not use raise_errors
RemovedCharacter.model_rebuild(raise_errors=False)

