# coding: utf-8

"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.14.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from neucore_api.configuration import Configuration


class Watchlist(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'lock_watchlist_settings': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'lock_watchlist_settings': 'lockWatchlistSettings'
    }

    def __init__(self, id=None, name=None, lock_watchlist_settings=None, local_vars_configuration=None):  # noqa: E501
        """Watchlist - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._lock_watchlist_settings = None
        self.discriminator = None

        self.id = id
        self.name = name
        if lock_watchlist_settings is not None:
            self.lock_watchlist_settings = lock_watchlist_settings

    @property
    def id(self):
        """Gets the id of this Watchlist.  # noqa: E501


        :return: The id of this Watchlist.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Watchlist.


        :param id: The id of this Watchlist.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Watchlist.  # noqa: E501


        :return: The name of this Watchlist.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Watchlist.


        :param name: The name of this Watchlist.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def lock_watchlist_settings(self):
        """Gets the lock_watchlist_settings of this Watchlist.  # noqa: E501


        :return: The lock_watchlist_settings of this Watchlist.  # noqa: E501
        :rtype: bool
        """
        return self._lock_watchlist_settings

    @lock_watchlist_settings.setter
    def lock_watchlist_settings(self, lock_watchlist_settings):
        """Sets the lock_watchlist_settings of this Watchlist.


        :param lock_watchlist_settings: The lock_watchlist_settings of this Watchlist.  # noqa: E501
        :type: bool
        """

        self._lock_watchlist_settings = lock_watchlist_settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Watchlist):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Watchlist):
            return True

        return self.to_dict() != other.to_dict()
