# coding: utf-8

# flake8: noqa

"""
    Neucore API

    Client library of Neucore API  # noqa: E501

    The version of the OpenAPI document: 1.9.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from neucore_api.api.application_api import ApplicationApi

# import ApiClient
from neucore_api.api_client import ApiClient
from neucore_api.configuration import Configuration
from neucore_api.exceptions import OpenApiException
from neucore_api.exceptions import ApiTypeError
from neucore_api.exceptions import ApiValueError
from neucore_api.exceptions import ApiKeyError
from neucore_api.exceptions import ApiException
# import models into sdk package
from neucore_api.models.alliance import Alliance
from neucore_api.models.app import App
from neucore_api.models.character import Character
from neucore_api.models.character_groups import CharacterGroups
from neucore_api.models.corporation import Corporation
from neucore_api.models.corporation_member import CorporationMember
from neucore_api.models.esi_location import EsiLocation
from neucore_api.models.esi_type import EsiType
from neucore_api.models.group import Group
from neucore_api.models.group_application import GroupApplication
from neucore_api.models.player import Player
from neucore_api.models.removed_character import RemovedCharacter
from neucore_api.models.role import Role
from neucore_api.models.system_variable import SystemVariable

